# Generated by Django 4.2.16 on 2024-11-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
